test:
	g++ thread.cc test.cc -o test libcpu.a -ldl -pthread -std=c++11

test1:
	g++ thread.cc test1.cc -o test1 libcpu.a -ldl -pthread -std=c++11

test2:
	g++ thread.cc test2.cc -o test2 libcpu.a -ldl -pthread -std=c++11

test3:
	g++ thread.cc test3.cc -o test3 libcpu.a -ldl -pthread -std=c++11

test4:
	g++ thread.cc test4.cc -o test4 libcpu.a -ldl -pthread -std=c++11

test5:
	g++ thread.cc test5.cc -o test5 libcpu.a -ldl -pthread -std=c++11

test6:
	g++ thread.cc test6.cc -o test6 libcpu.a -ldl -pthread -std=c++11

test7:
	g++ thread.cc test7.cc -o test7 libcpu.a -ldl -pthread -std=c++11

test8:
	g++ thread.cc test8.cc -o test8 libcpu.a -ldl -pthread -std=c++11

test9:
	g++ thread.cc test9.cc -o test9 libcpu.a -ldl -pthread -std=c++11

test9simple1:
	g++ thread.cc test9simple1.cc -o test9simple1 libcpu.a -ldl -pthread -std=c++11

test9simple2:
	g++ thread.cc test9simple2.cc -o test9simple2 libcpu.a -ldl -pthread -std=c++11

test10:
	g++ thread.cc test10.cc -o test10 libcpu.a -ldl -pthread -std=c++11

test11:
	g++ thread.cc test11.cc -o test11 libcpu.a -ldl -pthread -std=c++11

test12:
	g++ thread.cc test12.cc -o test12 libcpu.a -ldl -pthread -std=c++11

test13:
	g++ thread.cc test13.cc -o test13 libcpu.a -ldl -pthread -std=c++11

test14:
	g++ thread.cc test14.cc -o test14 libcpu.a -ldl -pthread -std=c++11

test15:
	g++ thread.cc test15.cc -o test15 libcpu.a -ldl -pthread -std=c++11

test16:
	g++ thread.cc test16.cc -o test16 libcpu.a -ldl -pthread -std=c++11

test17:
	g++ thread.cc test17.cc -o test17 libcpu.a -ldl -pthread -std=c++11

test18:
	g++ thread.cc test18.cc -o test18 libcpu.a -ldl -pthread -std=c++11

testforcpu:
	g++ thread.cc testforcpu.cc -o testforcpu libcpu.a -ldl -pthread -std=c++11

lot:
	g++ thread.cc lotofmutex.cc -o lot libcpu.a -ldl -pthread -std=c++11

run:
	./test >output1

clean:
	rm -rf test testp1 testp2 test1 test2 test3 test4 test5 test6 test7 test8 test9 test10 test11 test12 test13 test14 test15 test16 test17 test18 test9simple1 test9simple2 testforcpu lot

